version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: backstage-db
    restart: always
    environment:
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage_plugin_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backstage:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: backstage-app
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage
      POSTGRES_DB: backstage_plugin_app
    ports:
      - "7007:7007"

volumes:
  postgres_data:
