services:
  postgres:
    image: postgres:15
    container_name: backstage-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "backstage", "-d", "postgres"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s

  backstage:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: backstage-app
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
      BACKSTAGE_BASE_URL: ${BACKSTAGE_BASE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT}:${PORT}"  # Expose the app on the port defined in your .env (e.g., 8080)

volumes:
  postgres_data:
